# Generated by Django 2.0.5 on 2018-08-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('memberlimits', models.IntegerField(default=200)),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admins', to='webuser.Webuser')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webuser.Webuser')),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to='webuser.Webuser')),
            ],
        ),
    ]
